### ISSUE TITLE
Monoid instance for App

### ISSUE THREAD

**Issue by hdgarrood** [purescript/purescript-functors#12]
I think it might be nice to give `App` the following instances:

```purescript
instance semigroupApp :: Apply f => Semigroup (App f a) where
  append (App x) (App y) = App (x *> y)

instance monoidApp :: Applicative f => Monoid (App f Unit) where
  mempty = App (pure unit)
```

Unresolved questions:

1. `App` already inherits a `Plus` instance from `f` if one exists. Since `Plus` is basically `Monoid1`, is it potentially surprising to have two differing monoid-like instances on `App`?
2. Would it make more sense to use `Unit` or an unconstrained type variable in the `Semigroup` instance? I suppose the former, since it still works and is more general?

**Comment by paf31** [comment]
I was actually thinking something like `append (App x) (App y) = App (lift2 append x y)`.

**Comment by hdgarrood** [comment]
Ah, of course. That works too, and is probably more in line with App's existing instances, I suppose.

**Comment by hdgarrood** [comment]
Oh, silly me, I only just realised it would be the same as the instance I'm proposing for `App f Unit`!
